server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:1523
          predicates:
            - Path=/doctor/**
        - id: patient-service
          uri: http://localhost:1521
          predicates:
            - Path=/**